---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg12

description: tg12b desc

conditions:
  anyOf:
    - property:
        name: rox.screen_height
        operator: is-undefined
